[package]
name = "rust-http-kafka-bridge"
version = "0.1.0"
authors = ["Michael Poirier <mikepoirier26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
